#!/bin/sh /etc/rc.common

USE_PROCD=1

START=98
STOP=01

DAEMON="/usr/bin/qbittorrent-nox"
ARGS="--profile=/tmp"

start_service() {
	procd_open_instance
	procd_set_param command "$DAEMON" "$ARGS"
	procd_close_instance
}
